### ISSUE TITLE
2016 Meetup Talks esp. D3JS

### ISSUE THREAD

**Issue by suranands** [Chennaipy/talks#18]
Hi, 

I was wondering if this repo is being updated with the 2016 talks, or did I miss the content somewhere.

Especially, I learned that you have covered D3 visualizations in one of the recent meetups. Is there any way I can access such material, I would be very interested?

Thanks.
Anand

**Comment by hazeez** [comment]
Hi,

The repo has been updated now and is waiting for the admin (chennaipy) to close the pull request. Hopefully this will be done within this week.

The talk you mentioned didn't happen on the meetup day as the speaker didn't turn up. I was eagerly expecting this talk but it did not happen. Can you try your hands here and give a talk on this topic someday?

Thanks
Azeez

**Comment by kirang89** [comment]
@asinode Unfortunately, none of us have been updating the repo. But thanks to @hazeez and his PR #19, we have a something to go with. We'll take care in updating this from now on.

**Comment by suranands** [comment]
@kirang89 thanks for letting me know. 

@hazeez thanks for your efforts. I would love to give a talk. However,  I am pretty new in the world of core python. Giving a talk on using python in combo with D3 kind of frameworks will be a bit too ambitious at this time. I will come forward once I feel there is a topic that I can cover at least to a significant level. Thanks for encouraging.

**Comment by kirang89** [comment]
> I will come forward once I feel there is a topic that I can cover at least to a significant level. 

@asinode I'd recommend starting with giving a lightning talk. It'd could about anything (library/framework/code snippet/tools or anything related to Computer Science in general) that you think people might find interesting.

**Comment by hazeez** [comment]
I cannot agree more with @kirang89. Lightning talks will act as the ice breaker and a testing ground for a more lengthy talk.

**Comment by suranands** [comment]
Thanks both of you. This is truly inspiring. I will try to look through the topics and will come up with a lightening talk proposal soon.

**Comment by shrayasr** [comment]
Hi @asinode. I totally agree with @kirang89 and @hazeez. 

We had a thread on the mailing list sometime Jan last year as well. You might want to give that a read too :). I look forward to your talk proposal! 

---

Link: https://mail.python.org/pipermail/chennaipy/2015-January/000415.html

**Comment by shrayasr** [comment]
Also, closing this issue
